services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  maker-auth:
    build: ./maker-auth
    ports:
      - "8000:8000"
    env_file:
      - ./maker-auth/.env
    depends_on:
      - rabbitmq

  maker-app:
    build: ./maker-app
    ports:
      - "8001:8001"
    env_file:
      - ./maker-app/.env
    depends_on:
      - rabbitmq

  maker-app-consumer:
    build: ./maker-app
    command: python -m app.consumers.auth_consumer
    env_file:
      - ./maker-app/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      maker-auth:
        condition: service_started