# Generated by Django 6.0.6 on 2026-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerauth', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepts_marketing_contact',
            field=models.BooleanField(default=True),
        ),
    ]
