# Generated by Django 6.0.6 on 2026-09-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerauth', '0003_user_accepts_marketing_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
