# Generated by Django 6.0.6 on 2026-06-25 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('is_incubated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inep_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=7)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('fast', 'Fast'), ('childish', 'Childish'), ('technical', 'Technical')], max_length=9)),
                ('scheduling_date', models.DateTimeField()),
                ('has_visited', models.BooleanField(default=False)),
                ('forecast_number_of_visitors', models.IntegerField()),
                ('real_number_of_visitors', models.IntegerField(blank=True, null=True)),
                ('is_visit_closed', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visit_photos/')),
                ('observations', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('requester_origin', models.CharField(choices=[('cnat', 'CNAT'), ('school', 'School'), ('company', 'Company'), ('external', 'External')], max_length=8)),
                ('cnat_department', models.CharField(blank=True, choices=[('diatinf', 'DIATINF'), ('diaren', 'DIAREN'), ('diacon', 'DIACON'), ('diacin', 'DIACIN'), ('diac', 'DIAC')], max_length=7, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='makerapp.company')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='makerapp.school')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
    ]
