# Generated by Django 6.0.6 on 2026-09-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='inep_code',
        ),
    ]
