# Generated by Django 6.0.6 on 2026-09-09 01:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerapp', '0002_remove_school_inep_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('3d_printing', '3D Printing'), ('laser_cutting', 'Laser Cutting'), ('stamping', 'Stamping')], max_length=13)),
                ('file', models.FileField(upload_to='service_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'obj', 'jpg', 'jpeg', 'png'])])),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
