# Generated by Django 6.0.6 on 2026-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerapp', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
    ]
